# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c554c738d6b17376ff60fd64b6cc335f353caf19ef72c23ca774507fa8166904656cf929fd0a076cc5e542c442508c91001abfb2e4eeca73f7ba3ea431597b6

test:
  secret_key_base: 0e6e634eda2361b75a310c48e8bdfd5ca702e906900b4e8eefabd7c36fb697a01d5c85b5d659523b66790864f9cf4e48785748be96cf84f4b2313f89de02d02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
